component: scf
name: ap-chengdu_default_xrank
org: '1306888085'
app: xrank
stage: dev
inputs:
  name: xrank
  src: ./src
  runtime: Nodejs12.16
  region: ap-chengdu
  description: SCF created by Tencent Serverless Toolkit for VS Code
  handler: index.main_handler
  memorySize: 128
  timeout: 3
  events:
    - apigw:
        name: serverless_api
        parameters:
          protocols:
            - http
            - https
          description: The service of Serverless Framework
          environment: release
          endpoints:
            - path: /
              method: GET

# For more information: https://github.com/serverless-components/tencent-scf/blob/master/docs/configure.md